name: "build"
on:                                                                                                                                                                                                    
  push:                                                                                                                                                                                                
    branches:                                                                                                                                                                                          
      - llvm-with-clang-for-32bit-arm-host
  workflow_dispatch:

jobs:

  build:
      runs-on: ubuntu-latest

      steps:
       - uses: actions/checkout@v3
       - run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
       - name: run
       - run: exec ./main.sh
       - uses: "marvinpinto/action-automatic-releases@latest"
           with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development build ${{ env.SHORT_SHA }}"
             files: |
                    llvm-sysroot.tar.gz
